# File: setup-vm.yml
# An Ansible playbook to configure a new Debian 12 VM.
---
- name: Configure New Debian VM
  hosts: all
  become: yes # Use 'sudo' for tasks by default

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      # We don't want this to show as a "change" every time
      changed_when: false

    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - git-all
          - gh # GitHub CLI
          - zsh
          - ranger
          - build-essential # Often needed for compiling/installing from source
        state: present # Ensures these packages are installed

    - name: Set Zsh as default shell in .bashrc
      become: no # This task must run as the user, not root
      ansible.builtin.blockinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        create: yes # Create the file if it doesn't exist
        marker: "# {mark} ANSIBLE MANAGED BLOCK - ZSH"
        block: |
          # Launch Zsh if it's installed
          if [ -x /usr/bin/zsh ]; then
            exec /usr/bin/zsh
          fi

    - name: Clone fzf from GitHub
      ansible.builtin.git:
        repo: "https://github.com/junegunn/fzf.git"
        dest: "/home/{{ ansible_user }}/.fzf"
        depth: 1
      become: no # Run this as the user, not root

    - name: Run fzf install script in zsh
      ansible.builtin.shell:
        cmd: "zsh -c './install --all'"
        chdir: "/home/{{ ansible_user }}/.fzf"
      become: no
      # This task will only run if the fzf binary doesn't exist yet
      args:
        creates: "/home/{{ ansible_user }}/.fzf/bin/fzf"

    - name: Install zoxide
      become: no # Run this as the user, not root
      ansible.builtin.shell: >
        curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
      # This makes the task idempotent. It only runs if zoxide isn't already installed.
      args:
        creates: "/home/{{ ansible_user }}/.local/bin/zoxide"

    - name: Check if Oh My Zsh is already installed
      become: no
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.oh-my-zsh"
      register: oh_my_zsh_stats

    - name: Install Oh My Zsh
      become: no
      ansible.builtin.shell: >
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      when: not oh_my_zsh_stats.stat.exists # Only run if the folder doesn't exist
