# Customize spaceship prompt 
# ORDER
SPACESHIP_PROMPT_ORDER=(
    venv # virtual environemnt
    uv # uv based virtual environment
    conda # conda virtual environment
    user
    dir
    host
    char
) 
SPACESHIP_RPROMPT_ORDER=(
    git
)
# GENERAL SETUP
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=false
#SPACESHIP_PROMPT_DEFAULT_PREFIX="@"
#SPACESHIP_PROMPT_DEFAULT_SUFFIX=
# CHAR
SPACESHIP_CHAR_SYMBOL=">>"
SPACESHIP_CHAR_PREFIX=""
SPACESHIP_CHAR_SUFFIX=" "
# USER
# SPACESHIP_USER_PREFIX="" # remove `with` before username
# SPACESHIP_USER_SUFFIX="" # remove space before host
# TIME 
SPACESHIP_TIME_SHOW=false
# HOST
# Result will look like this:
#   username@:hostname)
SPACESHIP_USER_SHOW=true
SPACESHIP_HOST_PREFIX="@:"
SPACESHIP_HOST_SUFFIX=" "

# DIR
SPACESHIP_DIR_PREFIX="" 
SPACESHIP_DIR_SUFFIX=" "
SPACESHIP_DIR_TRUNC=1 # show only last directory
SPACESHIP_DIR_TRUNC_REPO=false # no special treatment of git repository
SPACESHIP_DIR_COLOR='yellow'
# GIT
# Disable git symbol
#SPACESHIP_GIT_SYMBOL="" # disable git prefix
#SPACESHIP_GIT_BRANCH_PREFIX="" # disable branch prefix too
# Wrap git in `git:...)`
SPACESHIP_GIT_PREFIX='git:'
SPACESHIP_GIT_SUFFIX=" "
#SPACESHIP_GIT_BRANCH_SUFFIX="" # remove space after branch name
## Unwrap git status from `[...]`
#SPACESHIP_GIT_STATUS_PREFIX=""
#SPACESHIP_GIT_STATUS_SUFFIX=""

# NODE
SPACESHIP_NODE_PREFIX="node:"
SPACESHIP_NODE_SUFFIX=" "
SPACESHIP_NODE_SYMBOL=""

# RUBY
SPACESHIP_RUBY_PREFIX="ruby:"
SPACESHIP_RUBY_SUFFIX=" "
SPACESHIP_RUBY_SYMBOL=""

# XCODE
SPACESHIP_XCODE_PREFIX="xcode:"
SPACESHIP_XCODE_SUFFIX=" "
SPACESHIP_XCODE_SYMBOL=""

# SWIFT
SPACESHIP_SWIFT_PREFIX="swift:"
SPACESHIP_SWIFT_SUFFIX=" "
SPACESHIP_SWIFT_SYMBOL=""

# GOLANG
SPACESHIP_GOLANG_PREFIX="go:"
SPACESHIP_GOLANG_SUFFIX=" "
SPACESHIP_GOLANG_SYMBOL=""

# DOCKER
SPACESHIP_DOCKER_PREFIX="docker:"
SPACESHIP_DOCKER_SUFFIX=" "
SPACESHIP_DOCKER_SYMBOL=""

# CONDA
SPACESHIP_CONDA_PREFIX=""
SPACESHIP_CONDA_COLOR='blue'
# VENV
SPACESHIP_VENV_PREFIX="venv:"
SPACESHIP_VENV_SUFFIX=" "

# PYENV
SPACESHIP_PYTHON_PREFIX="python:"
SPACESHIP_PYTHON_SUFFIX=" "
SPACESHIP_PYENV_SYMBOL=""

# GCLOUD
SPACESHIP_GCLOUD_SHOW=true
SPACESHIP_GCLOUD_ASYNC=true